modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="sinker"
version="${file.jarVersion}"
displayName="Sinker"
logoFile="sinker.png"
credits="Developed by Moomallowz, textured by AshesUponAshes"
authors="Created by the Merchant Modding Team"
description='''
A lightweight fishing mod that aims to revitalize and incentivize fishing by adding new mechanics, loot, and food
'''